[package]
name = "prompt2shell"
version = "0.1.0"
edition = "2021"

[dependencies]
openai-api-rs = "0.1.5"
tokio = { version = "1", features = ["full"] }
colored = "2.0.0"
clap = "3.0"
log = "0.4"
simplelog = "0.11"
rustyline = "8.0.0"
